#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM nginx:latest
COPY proxy.conf /etc/nginx/conf.d/proxy.conf
EXPOSE 8080
